import { useEffect, useState } from 'react';
import { Bell, ChevronDown, Filter, LayoutGrid, LogOut, Plus, Search, Sparkles, Users } from 'lucide-react';
import { connectSocket } from '../services/socket';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import Column from './Column';

const columns = [{ key: 'backlog', label: 'Backlog' }, { key: 'inProgress', label: 'In progress' }, { key: 'review', label: 'Review' }, { key: 'done', label: 'Done' }];
const demoTasks = [{ _id: '1', title: 'Shape the product story', description: 'Clarify the narrative for the next release and align the team around it.', status: 'backlog', priority: 'high', dueDate: '2026-08-26' }, { _id: '2', title: 'Map the onboarding flow', description: 'Turn the first-run experience into something that feels effortless.', status: 'backlog', priority: 'medium', dueDate: '2026-08-29' }, { _id: '3', title: 'Build the activity feed', description: 'A living view of the work as it moves through the board.', status: 'inProgress', priority: 'high', dueDate: '2026-08-23' }, { _id: '4', title: 'Review empty states', description: 'Make every quiet moment feel considered.', status: 'review', priority: 'low' }, { _id: '5', title: 'Ship the first release', description: 'Celebrate the small beginning.', status: 'done', priority: 'medium' }];
export default function Board() { const { user, logout } = useAuth(); const [tasks, setTasks] = useState(demoTasks); const [boardId, setBoardId] = useState(null); const [query, setQuery] = useState(''); const [showAdd, setShowAdd] = useState(false); const [newTitle, setNewTitle] = useState('');
  useEffect(() => { let socket; api.get('/boards').then(({ data }) => data[0] && api.get(`/boards/${data[0]._id}`).then(({ data: detail }) => { setBoardId(detail.board._id); setTasks(detail.tasks); })).catch(() => {}); socket = connectSocket(); socket.on('taskChanged', task => setTasks(current => current.some(item => item._id === task._id) ? current.map(item => item._id === task._id ? task : item) : [...current, task])); return () => socket.disconnect(); }, []);
  useEffect(() => { if (boardId) { const socket = connectSocket(); socket.emit('joinBoard', boardId); return () => socket.disconnect(); } }, [boardId]);
  async function moveTask(id, status) { setTasks(current => current.map(task => task._id === id ? { ...task, status } : task)); if (id.length > 10) { try { const { data } = await api.patch(`/tasks/${id}`, { status }); const socket = connectSocket(); socket.emit('taskChanged', { boardId, task: data }); socket.disconnect(); } catch {} } }
  async function addTask() { if (!newTitle.trim()) return; const task = { _id: crypto.randomUUID(), title: newTitle.trim(), status: 'backlog', priority: 'medium' }; setTasks(current => [task, ...current]); setNewTitle(''); setShowAdd(false); if (boardId) { try { const { data } = await api.post('/tasks', { board: boardId, title: task.title }); setTasks(current => current.map(item => item._id === task._id ? data : item)); } catch {} } }
  const visible = tasks.filter(task => task.title.toLowerCase().includes(query.toLowerCase()));
  return <main className="app-shell"><aside className="sidebar"><div className="sidebar-brand">tf<span>/</span><small>taskflow</small></div><nav><p className="nav-label">Workspace</p><a className="active"><LayoutGrid size={17}/> My board</a><a><Users size={17}/> Team</a></nav><div className="sidebar-bottom"><div className="tip"><Sparkles size={16}/><strong>Keep it moving</strong><p>Small progress is still progress.</p></div><button className="user-chip" onClick={logout}><span className="avatar">{user?.name?.[0] || 'A'}</span><span>{user?.name || 'Demo user'}<small>Sign out</small></span><LogOut size={15}/></button></div></aside><section className="workspace"><header className="topbar"><div className="crumb"><span>Workspace</span><b>/</b><strong>My board</strong></div><div className="top-actions"><button className="icon-button"><Bell size={18}/></button><div className="avatar-group"><span className="avatar peach">J</span><span className="avatar mint">S</span><span className="avatar more">+3</span></div><button className="share-button"><Users size={16}/> Share</button></div></header><div className="board-wrap"><div className="board-heading"><div><p className="eyebrow">Tuesday, August 21</p><h1>Product launch <span>↗</span></h1><p className="board-description">A clear view of the work that gets us there.</p></div><button className="add-button" onClick={() => setShowAdd(true)}><Plus size={17}/> Add task</button></div><div className="board-tools"><div className="search"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search tasks..."/></div><button className="filter-button"><Filter size={15}/> Filter <ChevronDown size={14}/></button><span className="board-status"><i></i> Live board</span></div><div className="board-grid">{columns.map(column => <Column key={column.key} column={column} tasks={visible.filter(task => task.status === column.key)} onMove={moveTask} onAdd={() => setShowAdd(true)}/>)}</div></div></section>{showAdd && <div className="modal-backdrop" onClick={() => setShowAdd(false)}><form className="modal" onSubmit={e => { e.preventDefault(); addTask(); }} onClick={e => e.stopPropagation()}><p className="eyebrow">New task</p><h2>What needs doing?</h2><input autoFocus value={newTitle} onChange={e => setNewTitle(e.target.value)} placeholder="Give it a clear name"/><div className="modal-actions"><button type="button" onClick={() => setShowAdd(false)}>Cancel</button><button className="primary-button" type="submit">Add task <Plus size={16}/></button></div></form></div>}</main>; }
