import { useState } from 'react';
import { ArrowRight, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export default function Signup({ onSwitch }) {
  const [values, setValues] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const { authenticate } = useAuth();
  async function submit(e) { e.preventDefault(); setError(''); try { await authenticate('signup', values); } catch (err) { setError(err.response?.data?.message || 'Unable to create account'); } }
  return <main className="auth-page"><section className="auth-visual"><div className="brand-mark">tf<span>/</span></div><div className="visual-copy"><p className="eyebrow">The calm way to ship</p><h1>Bring order<br/>to the busy.</h1><div className="mini-note">✦ &nbsp; Focus on the work that moves</div></div><div className="visual-footer">TASKFLOW / 2026</div></section><section className="auth-panel"><div className="auth-content"><div className="mobile-brand">tf<span>/</span></div><p className="eyebrow">Start your workspace</p><h2>Good work,<br/>in motion.</h2><p className="auth-copy">Create a focused home for the work your team is proud of.</p><form onSubmit={submit} className="auth-form"><label><span>Your name</span><div className="input-wrap"><UserRound size={17}/><input required value={values.name} onChange={e => setValues({ ...values, name: e.target.value })} placeholder="Alex Morgan" /></div></label><label><span>Email</span><div className="input-wrap"><Mail size={17}/><input type="email" required value={values.email} onChange={e => setValues({ ...values, email: e.target.value })} placeholder="you@company.com" /></div></label><label><span>Password</span><div className="input-wrap"><LockKeyhole size={17}/><input type="password" minLength="6" required value={values.password} onChange={e => setValues({ ...values, password: e.target.value })} placeholder="At least 6 characters" /></div></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" type="submit">Create workspace <ArrowRight size={17}/></button></form><p className="switch-line">Already have an account? <button onClick={onSwitch}>Sign in</button></p></div></section></main>;
}
